const defaultPreset = require('./defaultPreset')

defaultPreset.darkMode = ['class', '[data-theme="dark"]']
defaultPreset.theme.colors = {
  current: 'currentColor',
  transparent: 'transparent',
  'black-alpha': 'rgba(0, 0, 0,.25)',
  black: 'rgb(var(--color-black) / <alpha-value>)',
  'base-1': 'rgb(var(--color-base-1) / <alpha-value>)',
  'base-2': 'rgb(var(--color-base-2) / <alpha-value>)',
  'base-3': 'rgb(var(--color-base-3) / <alpha-value>)',
  'base-4': 'rgb(var(--color-base-4) / <alpha-value>)',
  'inverted-1': 'rgb(var(--color-inverted-1) / <alpha-value>)',
  'inverted-2': 'rgb(var(--color-inverted-2) / <alpha-value>)',
  'inverted-3': 'rgb(var(--color-inverted-3) / <alpha-value>)',
  'inverted-4': 'rgb(var(--color-inverted-4) / <alpha-value>)',
  'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
  'on-sucess': 'rgb(var(--color-on-sucess) / <alpha-value>)',
  'on-danger': 'rgb(var(--color-on-danger) / <alpha-value>)',
  'on-warning': 'rgb(var(--color-on-warning) / <alpha-value>)',
  'on-inverted': 'rgb(var(--color-on-inverted) / <alpha-value>)',
  'on-base': 'rgb(var(--color-on-base) / <alpha-value>)',
  'on-base-2': 'rgb(var(--color-on-base-2) / <alpha-value>)',
  'on-base-3': 'rgb(var(--color-on-base-3) / <alpha-value>)',
  'primary-light': 'rgb(var(--color-primary-light) / <alpha-value>)',
  primary: 'rgb(var(--color-primary) / <alpha-value>)',
  'primary-dark': 'rgb(var(--color-primary-dark) / <alpha-value>)',
  'primary-bold': 'rgb(var(--color-primary-bold) / <alpha-value>)',
  'tertiary-light': 'rgb(var(--color-tertiary-light) / <alpha-value>)',
  tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
  'tertiary-dark': 'rgb(var(--color-tertiary-dark) / <alpha-value>)',
  'tertiary-bold': 'rgb(var(--color-tertiary-bold) / <alpha-value>)',
  'success-light': 'rgb(var(--color-success-light) / <alpha-value>)',
  success: 'rgb(var(--color-success) / <alpha-value>)',
  'success-dark': 'rgb(var(--color-success-dark) / <alpha-value>)',
  'success-bold': 'rgb(var(--color-success-bold) / <alpha-value>)',
  'danger-light': 'rgb(var(--color-danger-light) / <alpha-value>)',
  danger: 'rgb(var(--color-danger) / <alpha-value>)',
  'danger-dark': 'rgb(var(--color-danger-dark) / <alpha-value>)',
  'danger-bold': 'rgb(var(--color-danger-bold) / <alpha-value>)',
  'warning-light': 'rgb(var(--color-warning-light) / <alpha-value>)',
  warning: 'rgb(var(--color-warning) / <alpha-value>)',
  'warning-dark': 'rgb(var(--color-warning-dark) / <alpha-value>)',
  'warning-bold': 'rgb(var(--color-warning-bold) / <alpha-value>)',
  'secondary-light': 'rgb(var(--color-secondary-light) / <alpha-value>)',
  secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
  'secondary-dark': 'rgb(var(--color-secondary-dark) / <alpha-value>)',
  'secondary-bold': 'rgb(var(--color-secondary-bold) / <alpha-value>)',
  'orange-promax': 'rgb(var(--color-orange-promax) / <alpha-value>)',
  google: 'rgb(var(--color-google) / <alpha-value>)',
  'google-dark': 'rgb(var(--color-google-dark) / <alpha-value>)',
  'google-bold': 'rgb(var(--color-google-bold) / <alpha-value>)',
  'google-red': 'rgb(var(--color-google-red) / <alpha-value>)',
  'google-blue': 'rgb(var(--color-google-blue) / <alpha-value>)',
  'google-purple': 'rgb(var(--color-google-purple) / <alpha-value>)',
  'google-green': 'rgb(var(--color-google-green) / <alpha-value>)',
  'google-yellow': 'rgb(var(--color-google-yellow) / <alpha-value>)',
  'card-stroke': 'rgb(var(--color-card-stroke) / <alpha-value>)',
  'card-stroke-2': 'rgb(var(--color-card-stroke-2) / <alpha-value>)',
  'card-shadow': 'rgb(var(--color-card-shadow) / <alpha-value>)',
  focus: 'rgb(var(--color-focus) / <alpha-value>)',
  'focus-light': 'rgb(var(--color-focus-light) / <alpha-value>)',
  'focus-dark': 'rgb(var(--color-focus-dark) / <alpha-value>)',
}

module.exports = defaultPreset
