name: CI Styleguide

# on:   
#   push:
#     branches-ignore:
#       - 'main'
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: styleguide
      
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: styleguide

      - name: Lint
        run: yarn lint
        working-directory: styleguide

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        working-directory: styleguide

      - name: Build
        run: yarn build
        working-directory: styleguide
