name: CI Styleguide

# on:
#   push:
#     branches-ignore:
#       - 'main'
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: styleguide

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [self-hosted]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Intall cypress deps
        run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
        working-directory: styleguide

      - name: Install NPM deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: styleguide

      - name: Lint
        run: yarn lint
        working-directory: styleguide

      - name: Test Jest
        run: yarn test:jest --ci --coverage --maxWorkers=2
        working-directory: styleguide

      - name: Test Cypress
        run: yarn test:cypress:ci
        working-directory: styleguide

      - name: Build
        run: yarn build
        working-directory: styleguide
