name: Monorepo PR Repo Labeler

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  labelPR:
    name: Label PR With Repo(s)
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: TinkurLab/monorepo-pr-labeler-action@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
