name: Publish Styleguide

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: styleguide

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ startsWith('refs/tags/styleguide@', github.ref) }}
    # if: "'refs/heads/main' == github.ref && startsWith(github.ref, 'refs/tags/styleguide@')"
    if: ${{ github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/styleguide@') }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: styleguide

      - name: Update version
        run: yarn version --new-version "${GITHUB_REF#refs/tags/styleguide@}" --no-git-tag-version
        working-directory: styleguide

      - name: Publish to NPM
        run: yarn publish --access public
        working-directory: styleguide
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_STYLEGUIDE }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Published tag ${GITHUB_REF:11}
          file_pattern: styleguide/package.json

      - name: Send to GitHub Pages 🔧
        run: yarn deploy-storybook --ci --source-branch=main
        working-directory: styleguide
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
