name: Publish Tailwindcss

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: tailwindcss

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/tailwindcss@') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_COMMIT_MAIN }}
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: tailwindcss

      - name: Update version
        run: yarn version --new-version "${GITHUB_REF#refs/tags/tailwindcss@}" --no-git-tag-version
        working-directory: tailwindcss

      - name: Publish to NPM
        run: yarn publish --access public
        working-directory: tailwindcss
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_STYLEGUIDE }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Published tag for Tailwindcss
          branch: main
          push_options: --force
          file_pattern: tailwindcss/package.json

